name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build with Buildozer
        uses: GearSnd/buildozer-action@v1
        with:
          command: buildozer android debug
          repository_display_name: AntivirusShield
          
